apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-route
  namespace: beginner-nginx
spec:
  parentRefs:
    - name: public-gateway
      namespace: platform-gateway
  hostnames:
    - "48.216.181.196.nip.io"
  rules:
    - backendRefs:
        - name: nginx
          port: 80